name: Push to Gitee
on:
  workflow_run:
    workflows: ["Published to GitHub Pages"]
    types:
    - completed
jobs:
  push-to-gitee:
    runs-on: ubuntu-latest
    name: "Push to Gitee"

    
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    steps: 
     - name: Checkout
       uses: actions/checkout@v2

     - name: Switch branch
       run: git fetch && git checkout gh-pages && git pull

     - name: Add Remote
       run: git remote add gitee https://oauth2:${{secrets.GITEE_TOKEN}}@gitee.com/diaz/diaz.git

     - name: Push to gitee
       run: git push gitee